const TEMP_EMAIL_DOMAINS = [
  '10minutemail.com',
  '10mail.org',
  '123mail.club',
  '123mail.org',
  '1clickemail.com',
  '20mail.it',
  '24mail.pw',
  '2prong.com',
  '30minutemail.com',
  '4mail.in',
  '5mail.net',
  '60minutemail.com',
  'a-bc.net',
  'abyssmail.com',
  'acid-mail.com',
  'airmail.net',
  'anonbox.net',
  'anonemail.net',
  'bcemail.co.uk',
  'bigstring.com',
  'blueturtle.info',
  'bodhi.lawlita.com',
  'breakermail.com',
  'browntape.com',
  'bugmenot.com',
  'burnermail.io',
  'c2.hu',
  'chogmail.com',
  'cloakmail.com',
  'cmail.com',
  'concealmentmail.com',
  'cool.fr.nf',
  'courriel.fr.nf',
  'dacoolest.com',
  'deadaddress.com',
  'despammed.com',
  'discard.email',
  'dispostable.com',
  'dodgeit.com',
  'dontreg.com',
  'dump-email.info',
  'dumpmail.de',
  'dummymail.de',
  'email60.com',
  'emailalias.com',
  'emaildisposable.com',
  'emailfake.com',
  'emailsac.com',
  'emailtemporaire.fr',
  'emailtmp.com',
  'emailto.de',
  'ephemeral-mail.com',
  'evopo.com',
  'fakeemailgenerator.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'fakemailz.com',
  'fastmail.fm',
  'filzmail.com',
  'firedrop.de',
  'fixmail.com',
  'getairmail.com',
  'getmailspring.com',
  'ghosttexter.com',
  'gishpuppy.com',
  'gmx.com',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'hadesmail.com',
  'harakirimail.com',
  'hayseed.net',
  'hiddemail.com',
  'hot-mail.biz',
  'ieatspam.net',
  'imgmail.net',
  'incognitomail.com',
  'inboxclean.com',
  'inboxproxy.com',
  'inboxr.com',
  'instantemailaddress.com',
  'intermail.net',
  'ip6.li',
  'jetable.fr',
  'jetable.net',
  'jetable.org',
  'kaspop.com',
  'koszmail.pl',
  'kurzepost.de',
  'lavabit.com',
  'leechblocker.com',
  'letthemeatspam.com',
  'lol.ovpn.to',
  'lolfreak.net',
  'mail.by',
  'mail.crazy-dns.com',
  'mail.eclipso.de',
  'mail.gd',
  'mail.metafilter.com',
  'mail.movie4k.to',
  'mail.org',
  'mailinator.com',
  'mailinator.net',
  'mailme.lv',
  'mailnesia.com',
  'mailnull.com',
  'mailzilla.com',
  'manybrain.com',
  'megamail.co',
  'mezzoinbox.com',
  'minimail.in',
  'moburl.com',
  'mohmal.com',
  'myspace.com',
  'neeko.com',
  'netmails.com',
  'netmails.net',
  'neverbox.com',
  'niftymail.com',
  'nomail.xl.cx',
  'nomail2me.com',
  'nowmymail.com',
  'oneoffemail.com',
  'onlinemailaccount.com',
  'onthefly.net',
  'optinbox.com',
  'pancakemail.com',
  'pastebin.mozilla.org',
  'pimpedmail.com',
  'postacard.com.au',
  'privacy.net',
  'proxymail.eu',
  'pupeye.com',
  'quickmail.nl',
  'rambler.ru',
  'realtymail.info',
  'recyclemail.dk',
  'regbypass.com',
  'rejectmail.com',
  'samair.ru',
  'sendspamhere.com',
  'sharklasers.com',
  'shiftmail.com',
  'silentpost.info',
  'sneakemail.com',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam4.me',
  'spamgourmet.com',
  'spamhole.com',
  'spamify.com',
  'spamlink.net',
  'spammotel.com',
  'spamspot.com',
  'speedymail.org',
  'swift-mail.com',
  'temp-mail.org',
  'tempemail.biz',
  'tempemail.com',
  'tempinbox.co.uk',
  'temporaryemail.net',
  'temporaryinbox.com',
  'tempmail.com',
  'tempmail.de',
  'tempmail.net',
  'tempmail.org',
  'tempmailer.com',
  'temp-mails.com',
  'throwawayemailaddress.com',
  'trash2009.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'trashmail.org',
  'trashymail.com',
  'trillianpro.com',
  'ultramail.si',
  'webm4il.info',
  'webmail4u.de',
  'wetrain.se',
  'wuzup.net',
  'xoxy.net',
  'yep.it',
  'ymail.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'zehnminutenmail.de',
  'zippymail.info',
];

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export interface EmailValidationResult {
  valid: boolean;
  message: string;
}

export function isValidEmailFormat(email: string): boolean {
  return EMAIL_REGEX.test(email.trim().toLowerCase());
}

export function isTemporaryEmail(email: string): boolean {
  const trimmedEmail = email.trim().toLowerCase();
  const domain = trimmedEmail.split("@")[1];
  if (!domain) return false;
  return TEMP_EMAIL_DOMAINS.includes(domain);
}

export function validateEmail(email: string): EmailValidationResult {
  const trimmedEmail = email.trim().toLowerCase();

  if (!isValidEmailFormat(trimmedEmail)) {
    return { valid: false, message: "请输入有效的邮箱地址" };
  }

  const domain = trimmedEmail.split("@")[1];
  if (!domain) {
    return { valid: false, message: "邮箱格式不正确" };
  }

  if (isTemporaryEmail(trimmedEmail)) {
    return { valid: false, message: "不允许使用临时邮箱注册，请使用正式邮箱地址" };
  }

  return { valid: true, message: "" };
}
